### ISSUE TITLE
Verifiy requests are actually coming from Slack

### ISSUE THREAD

**Issue by iampaul83** [iampaul83/yujack-slack-bot#3]
Use __Verification Token__ to verifiy requests are actually coming from Slack.

__Verification Token__ can be found in App Setting -> Basic information -> App Credentials

**Comment by iampaul83** [comment]
@Yu-Jack help

**Comment by Yu-Jack** [comment]
Okay, let me enhance the security.

p.s.
According the official documentation
"For interactive messages and events, use this token to verify that requests are actually coming from Slack. Slash commands and interactive messages will both use this verification token."

**Comment by iampaul83** [comment]
fixed by #4
